View Command Implementation and GUI fixes
AY2021S1-CS2103T-F11-4/tp pull request #125
Opened 2020-10-10 16:04 UTC by LeeEnHao

Fixes #104 
Fixes #110

2020-10-10 17:06 UTC, tankangliang commented on src/main/java/seedu/address/logic/commands/ClientViewCommand.java
> +    of the rendered */
```suggestion
    /** Client command in the form client view index, where index points to the index of the client at current location
    of the rendered */
```

2020-10-10 17:33 UTC, LeeEnHao reviewed
Squash

2020-10-11 09:11 UTC, LeeEnHao commented
Adding of the view box to the GUI will be done in separate branch in case GUI breaks.

2020-10-11 17:32 UTC, tankangliang requested changes
Tested `client view` with negative index, valid index and non-numbers and seems to be working fine. Thanks for adding the icon and title for TBM. Haven't been able to look at widget component but it doesn't seem to be affecting any functionality. Other than minor javadoc comments, looks good to merge.

2020-10-11 17:32 UTC, tankangliang commented on src/main/java/seedu/address/logic/Logic.java
> +     * @return
Should fill in the javadoc here

2020-10-11 17:32 UTC, tankangliang commented on src/main/java/seedu/address/logic/commands/ClientViewCommand.java
> +    /*Client command in the form client view index, where index points to the index of the client at current location
```suggestion
    /** Client command in the form client view index, where index points to the index of the client at current location
```
To be more inline with the coding standards 
![image](https://user-images.githubusercontent.com/1027621/95684984-a10a5980-0c27-11eb-8e4b-4f244a66c683.png)

2020-10-11 17:32 UTC, tankangliang commented on src/main/java/seedu/address/logic/parser/ViewCommandParser.java
> +public class ViewCommandParser implements Parser<ClientViewCommand> {
Could you change the class and file name to `ClientViewCommandParser`? I will be updating the ones for Find and Delete in a future PR

2020-10-11 17:32 UTC, tankangliang commented on src/main/java/seedu/address/model/widget/WidgetModel.java
> +     * @return
Missing javadoc for return here too

2020-10-11 19:01 UTC, tankangliang commented on src/main/java/seedu/address/logic/commands/ClientViewCommand.java
> +    /**Client command in the form client view index, where index points to the index of the client at current location
```suggestion
    /** Client command in the form client view index, where index points to the index of the client at current location
```
Pls have the space there :(

2020-10-11 19:02 UTC, LeeEnHao commented on src/main/java/seedu/address/logic/commands/ClientViewCommand.java
> +    /**Client command in the form client view index, where index points to the index of the client at current location
Oh lol ps

2020-10-11 19:03 UTC, tankangliang approved these changes

2020-10-11 19:10 UTC, LeeEnHao commented
Integrity of Country behaviour seems intact. I'll merge now?

2020-10-11 23:55 UTC, raysonkoh approved these changes
Generally looks ok. Some minor concerns with `setWidgetContent` being in `Model` but if it works for now then this can be a future discussion/improvement.

2020-10-11 23:55 UTC, raysonkoh commented on src/main/java/seedu/address/model/Model.java
> +    void setWidgetContent(Object content);
Should `setWidgetContent` be in `Model`? Seems like this is mixing UI-related stuff with model-related stuff.

2020-10-12 02:12 UTC, merged