GUI test and systems test suites
AY2021S1-CS2103T-F11-4/tp pull request #197
Opened 2020-10-20 18:35 UTC by LeeEnHao

## Description

All Ui tests and integrated systems tests.

Fixes #194 #186 #189 #162 

## Testing
NIL
## Remarks

1. Build file shorts GitHub actions to skip Gui tests.

1. TestFX [Documentation](https://testfx.github.io/TestFX/docs/javadoc/)

2020-10-22 19:25 UTC, LeeEnHao commented
![image](https://user-images.githubusercontent.com/69501134/96920149-5f0ecc80-14df-11eb-8481-b7a86abd2914.png)

Ignore codecov.

2020-10-24 10:22 UTC, qwoprocks requested changes
Small changes

2020-10-24 10:22 UTC, qwoprocks commented on src/test/java/guitests/guihandles/MainMenuHandle.java
> +    }
These 2 functions don't seem to be used anymore

2020-10-24 10:22 UTC, qwoprocks commented on src/test/java/guitests/guihandles/StatusBarFooterHandle.java
> +    }
these functions dont seem to be used

2020-10-24 10:22 UTC, qwoprocks commented on src/test/java/seedu/address/ui/WidgetViewBoxTest.java
> +    }
Should this be paused for longer? I don't really notice it when I'm running the tests

2020-10-24 10:22 UTC, qwoprocks commented on src/test/java/seedu/address/ui/ClientListPanelTest.java
> +     */
Should add a TODO to remove this test at the end if we find that it's useless

2020-10-24 14:03 UTC, qwoprocks commented on src/test/java/seedu/address/ui/HelpWindowTest.java
> +        // Two tests are needed in fact.
Should probably remove this comment lol

2020-10-26 02:42 UTC, qwoprocks approved these changes
LGTM, except for the one small change

2020-10-26 02:42 UTC, qwoprocks commented on src/test/java/seedu/address/ui/CountryNoteCardTest.java
> +        assertEquals(expectedId + ". " + expectedCard.getNoteContents() + " [Singapore (SG)]",
```suggestion
        assertEquals(expectedId + ". " + expectedCard.getNoteContents() + " [" + expectedCard.getCountry() + "]",
```

2020-10-26 03:56 UTC, merged