Overdue updates to DG
AY2021S1-CS2103T-F11-4/tp pull request #363
Opened 2020-11-07 09:40 UTC by LeeEnHao

## Description

Removed proposed implementation for CommandHistory -> Implementation.

Fixes #351  

## Testing
NIL

## Remarks
NIL

2020-11-07 10:13 UTC, rtshkmr requested changes
Suggested some nits to look into

2020-11-07 10:13 UTC, rtshkmr commented on docs/DeveloperGuide.md
> +A command history greatly optimise the user's productivity by removing the need to repetitively type out similar commands.
```suggestion
A command history greatly optimises the user's productivity by removing the need to repetitively type out similar commands.
```

2020-11-07 10:13 UTC, rtshkmr commented on docs/DeveloperGuide.md
> +Furthermore, it allows backwards viewing of previous commands given, which is similar to the CLI experience. However, the difference between the traditional CLI history and TBM CLI history is that TB
```suggestion
Furthermore, it allows backwards viewing of previous commands given, which is similar to the CLI experience. However, the difference between the traditional CLI history and TBM CLI history is that TBM's history only accepts valid commands. Invalid commands entered will not be included will not appear in the command history.
```

2020-11-07 10:13 UTC, rtshkmr commented on docs/DeveloperGuide.md
> +The modification of previous commands in the history do not override the current command as well. The current input being edited is stored in a separate variable was the user scrolls through the comm
This sentence is a little confusing man 😟 

"The modification of previous commands ..." 
and 

also typo on the "was"  --> "as" probably

2020-11-08 07:13 UTC, raysonkoh commented on docs/DeveloperGuide.md
> +![User Command History Activity](images/CommandHistoryActivity.png))
Extra closing paren at end of this line

2020-11-08 09:23 UTC, raysonkoh approved these changes
LGTM

2020-11-08 09:27 UTC, rtshkmr approved these changes
LGTM

2020-11-08 09:28 UTC, merged