Update userguide with table of contents, quickstart, viewing help and adding clients section
AY2021S1-CS2103T-F11-4/tp pull request #51
Opened 2020-09-21 12:04 UTC by LeeEnHao

Fixes #15

2020-09-21 12:33 UTC, qwoprocks requested changes

2020-09-21 12:33 UTC, qwoprocks commented on docs/UserGuide.md
> +3. Double-click the file to start the app
I think we should retain the step of copying our jar file over to the folder the user wants to use as the home folder, as we'll need to do saving in a data folder as well

2020-09-21 12:33 UTC, qwoprocks commented on docs/UserGuide.md
> +you started in using TBM
There's inconsistency between this and the description of the help command below. Also, I think the help contents will be opened in a window and not a page?

2020-09-21 12:33 UTC, qwoprocks commented on docs/UserGuide.md
> +Shows a message explaining how to access the help page.
Refer to comment above

2020-09-21 12:33 UTC, qwoprocks commented on docs/UserGuide.md
> +Format: `client add n/NAME p/PHONE e/EMAIL a/ADDRESS c/COUNTRY tz/TIMEZONE`
Maybe we should change PHONE to PHONE_NUMBER, following the original format, for clarity

2020-09-21 13:47 UTC, LeeEnHao reviewed
Removed windows or pages. Left to implementation at later stage

2020-09-21 14:09 UTC, qwoprocks requested changes

2020-09-21 14:09 UTC, qwoprocks commented on docs/UserGuide.md
> +Shows a available commands for TBM.
```suggestion
Shows available commands for TBM.
```

2020-09-22 03:13 UTC, qwoprocks approved these changes

2020-09-22 03:14 UTC, merged